site_name: Mesop
repo_url: https://github.com/google/mesop
repo_name: google/mesop
nav:
  - Overview: index.md
  - Concepts: concepts.md
  - Components:
      - Box: components/box.md
      - Button: components/button.md
      - Checkbox: components/checkbox.md
      - Input: components/input.md
      - Text: components/text.md
      - Tooltip: components/tooltip.md
  - Features:
      - Pages: features/pages.md
  - Deployment: deployment.md
  - Troubleshooting: troubleshooting.md
  - Developing Mesop:
      - Goals: goals.md
      - New component: internal/new_component.md
      - Development: internal/development.md
      - Modes: internal/modes.md
      - Testing: internal/testing.md
      - Type checking: internal/type_checking.md
      - CI: internal/ci.md
      - Build / Toolchain: internal/toolchain.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png

  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: mesop-light
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: mesop-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.copy
    - navigation.path
    - navigation.instant

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true

  - pymdownx.superfences

plugins:
  - mkdocstrings:
      default_handler: python

      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: spacy
            heading_level: 1
            inherited_members: true
            merge_init_into_class: true
            separate_signature: false
            show_signature: false
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
