site_name: Mesop
repo_url: https://github.com/google/mesop
repo_name: google/mesop
strict: true
nav:
  - Overview: index.md
  - Getting Started: getting_started.md
  - Guides:
      - Components: guides/components.md
      - Interactivity: guides/interactivity.md
      - Pages: guides/pages.md
      - Deployment: guides/deployment.md
      - Troubleshooting: guides/troubleshooting.md
  - Components:
      - Layout:
          - Box: components/box.md
      - Text:
          - Text: components/text.md
          - Markdown: components/markdown.md
      - Media:
          - Image: components/image.md
          - Audio: components/audio.md
          - Video: components/video.md
      - Form controls:
          - Button: components/button.md
          - Checkbox: components/checkbox.md
          - Input: components/input.md
          - Textarea: components/textarea.md
          - Radio: components/radio.md
          - Select: components/select.md
          - Slide toggle: components/slide_toggle.md
          - Slider: components/slider.md
      - Visual:
          - Badge: components/badge.md
          - Divider: components/divider.md
          - Icon: components/icon.md
          - Progress bar: components/progress_bar.md
          - Progress spinner: components/progress_spinner.md
          - Tooltip: components/tooltip.md
  - Blog:
      - blog/index.md
  - Internal:
      - Architecture: internal/architecture.md
      - Goals: goals.md
      - New component: internal/new_component.md
      - Development: internal/development.md
      - Hot reload: internal/hot_reload.md
      - Modes: internal/modes.md
      - Testing: internal/testing.md
      - Type checking: internal/type_checking.md
      - CI: internal/ci.md
      - Build / Toolchain: internal/toolchain.md
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font:
    text: Poppins

  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: mesop-light
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: mesop-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.copy
    - navigation.path
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search.highlight

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true

  - pymdownx.superfences
  - pymdownx.snippets

plugins:
  - blog
  - search
  - mkdocstrings:
      default_handler: python

      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: spacy
            heading_level: 3
            inherited_members: true
            merge_init_into_class: true
            separate_signature: false
            show_signature: false
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
